const express = require("express");
const userMiddleware = require("../middleware/userMiddleware");
const Session = require("../models/emergencySession");
const Contact = require("../models/contact");
const { recordAttempt } = require("../agent/sessions");
const { createHandlers, verifyTwilio } = require("../agent/http");
const router = express.Router();
const handlers = createHandlers({ Session, Contact, recordAttempt, notify: event => require('../coordination/runtime').notify(event) });
router.use('/respond', require('./contactResponse'));
router.post("/webhooks/status", express.urlencoded({ extended: false, limit: "16kb" }), verifyTwilio, handlers.delivery);
router.post("/webhooks/incoming", express.urlencoded({ extended: false, limit: "16kb" }), verifyTwilio, handlers.incoming);
router.use(userMiddleware);
router.get('/diagnostics', handlers.diagnostics);
router.use(require('./coordination'));
router.get("/sessions", handlers.list);
router.get("/sessions/:id", handlers.detail);
router.post("/sessions/:id/resolve", handlers.resolve);
router.post("/sessions/:id/actions/:actionId/approve", handlers.approve);
router.post("/sessions/:id/actions/:actionId/reject", handlers.reject);
router.use((error, req, res, next) => {
  console.error("Agent API failed:", error.name);
  res.status(500).json({ error: "Agent request failed" });
});
module.exports = router;
